### ISSUE TITLE
Advanced Memory Footprint Reduction tutorial (memory scripts not available)

### ISSUE THREAD

**Issue by Martayugui** [preesm/preesm.github.io#17]
I am trying to access to the memory scripts provided by this tutorial (Advanced Memory Footprint Reduction) , however, the webpage is not available anymore.

Could you provide me with these memory scripts?

![image](https://user-images.githubusercontent.com/36645814/66275632-e664b000-e88a-11e9-82c9-c6d2b5721739.png)

Thank you

**Comment by antoine-morvan** [comment]
Website will be updated in few minutes.

**Comment by Martayugui** [comment]
Thank you,

I am working with memory scripts in order to reuse and reduce memory. I downloaded the scripts you have in the tutorial, but for special actors (broadcast,fork...) the memcpy calls are not removed properly during the code generation.

**Comment by antoine-morvan** [comment]
Please create a new issue
