### ISSUE TITLE
(Sobel) Single-rate visualization

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm.github.io#2]
In the sobel tutorial, it is asked to open the single-rate intermediate graph to understand its content.

2 problems arise:
- The DAG is exported by the given workflow, but not the single-rate graph.
- The graphml file can not be opened by latest version or Preesm.

**Comment by kdesnos** [comment]
Changing the extension of generated files from graphml to pi does the trick.

**Comment by antoine-morvan** [comment]
Fixed since https://github.com/preesm/preesm/releases/tag/v3.4.0 and https://github.com/preesm/preesm.github.io/commit/b3ef3f6123cbdf7ffec5e57899924bc704277095
