### ISSUE TITLE
(Tuto MDSP) Yuv2dat file is missing

### ISSUE THREAD

**Issue by kdesnos** [preesm/preesm.github.io#3]
When downloading the c6678 [source files](https://preesm.github.io/assets/tutos/mpsoccodegen/sobel_6678_sources.zip) for the C6678 project in the [Multicore DSP tutorial](https://preesm.github.io/tutos/mpsoccodegen/), the announced yuv2dat project is no longer included in the downloaded files.

**Comment by antoine-morvan** [comment]
Fixed by https://github.com/preesm/preesm.github.io/commit/456b5d7458f118ba5ca682da4c9b47022b2febc8
